# Generated by Django 6.1.1 on 2026-09-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_phoneotp_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='channel',
            field=models.CharField(choices=[('inapp', 'In-app (no SMS)'), ('email', 'Email')], default='inapp', help_text='How the OTP was delivered.', max_length=10),
        ),
    ]
