# Generated by Django 6.1.1 on 2026-09-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_phoneotp_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('inapp', 'In-app (no SMS)')], default='inapp', help_text='How the OTP was delivered.', max_length=10),
        ),
    ]
