# Generated by Django 6.1.1 on 2026-09-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_alter_phoneotp_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Normalised (lowercased) verified-at delivery address.', max_length=254)),
                ('purpose', models.CharField(choices=[('verify', 'Verify email')], max_length=10)),
                ('code_hash', models.CharField(max_length=128)),
                ('channel', models.CharField(choices=[('smtp', 'SMTP email'), ('console', 'Console (dev)')], default='console', help_text='How the code was delivered.', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False, help_text='Code already consumed (email verified → account created).')),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='True once the address on user.email has been verified via an email code or Google account.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='google_sub',
            field=models.CharField(blank=True, help_text='Google account subject ID (unique across all Google users).', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, db_index=True, help_text='Verified mobile number, e.g. 919876543210 (blank for Google / email-only accounts).', max_length=15, null=True, unique=True),
        ),
    ]
