# Generated by Django 6.1.1 on 2026-09-15 09:26

import django.db.models.deletion
import rental.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_emailcode_profile_email_verified_profile_google_sub_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='insurance_image',
            field=models.ImageField(blank=True, help_text='Uploaded insurance certificate photo.', null=True, upload_to=rental.models._insurance_upload),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_number',
            field=models.CharField(blank=True, help_text='Policy number of the vehicle insurance.', max_length=40),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_provider',
            field=models.CharField(blank=True, help_text='Insurance company name.', max_length=60),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_valid_until',
            field=models.DateField(blank=True, help_text='Insurance validity end date — used to check if the policy is still active.', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rc_image',
            field=models.ImageField(blank=True, help_text='Uploaded registration certificate (RC) photo.', null=True, upload_to=rental.models._rc_upload),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(blank=True, help_text='RC / registration number, e.g. MH01AB1234', max_length=20),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Final billable amount (set by the owner on completion).', max_digits=10, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('owner', models.ForeignKey(help_text='Snapshot of the vehicle owner when the trip started.', on_delete=django.db.models.deletion.CASCADE, related_name='trips_as_owner', to=settings.AUTH_USER_MODEL)),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_as_renter', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='rental.vehicle')),
            ],
            options={
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed_kmh', models.FloatField(default=0)),
                ('heading', models.FloatField(default=0)),
                ('accuracy_m', models.FloatField(default=0)),
                ('source', models.CharField(choices=[('gps', 'GPS device'), ('simulated', 'Simulated demo')], default='gps', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_updates', to='rental.vehicle')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='rental.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('accident', 'Accident'), ('damage', 'Damage'), ('theft', 'Theft'), ('breakdown', 'Breakdown')], max_length=10)),
                ('description', models.TextField()),
                ('incident_at', models.DateTimeField()),
                ('incident_location', models.CharField(blank=True, max_length=150)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('damage_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=rental.models._claim_upload)),
                ('photo2', models.ImageField(blank=True, null=True, upload_to=rental.models._claim_upload)),
                ('fir_number', models.CharField(blank=True, help_text='First Information Report (FIR) number from the police station.', max_length=40)),
                ('fir_station', models.CharField(blank=True, help_text='Police station where the FIR was registered.', max_length=100)),
                ('fir_image', models.ImageField(blank=True, help_text='Copy of the FIR document.', null=True, upload_to=rental.models._fir_upload)),
                ('status', models.CharField(choices=[('filed', 'Filed'), ('under_review', 'Under review'), ('approved', 'Approved for payout'), ('rejected', 'Rejected'), ('settled', 'Settled')], default='filed', max_length=15)),
                ('verified', models.BooleanField(default=False, help_text='Staff-verified as genuine (docs + FIR cross-checked).')),
                ('decision_note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_decisions', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='rental.vehicle')),
                ('trip', models.ForeignKey(blank=True, help_text='The rental trip this claim relates to (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='rental.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, help_text='A clear, recent photo of yourself.', null=True, upload_to=rental.models._verification_upload)),
                ('driving_license_no', models.CharField(blank=True, help_text='Driving licence number as printed on the card.', max_length=32)),
                ('driving_license_image', models.ImageField(blank=True, help_text='Front & back photo of the driving licence.', null=True, upload_to=rental.models._verification_upload)),
                ('aadhaar_no', models.CharField(blank=True, help_text='12-digit Aadhaar number (stored, displayed masked).', max_length=12)),
                ('aadhaar_image', models.ImageField(blank=True, help_text='Aadhaar card photo (masked version recommended).', null=True, upload_to=rental.models._verification_upload)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('review_note', models.CharField(blank=True, help_text='Public note left by the reviewer.', max_length=200)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
