# Generated by Django 6.1.1 on 2026-09-15 10:38

import rental.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_vehicle_insurance_image_vehicle_insurance_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload a clear photo of your vehicle.', null=True, upload_to=rental.models._vehicle_photo_upload),
        ),
    ]
