"""
Django settings for rentgo_project project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# ---- MySQL version gate workaround ---------------------------------------
# Django 6.x requires MySQL 8.4+, but this machine runs MySQL 8.0.46 which
# supports everything these models use. Skip the version check to let Django
# connect to the existing local MySQL server.
from django.db.backends.mysql import base as _mysql_base

_original_check = _mysql_base.DatabaseWrapper.check_database_version_supported

def _relaxed_version_check(self):
    return None

_mysql_base.DatabaseWrapper.check_database_version_supported = _relaxed_version_check


# ---- Local .env loader ---------------------------------------------
# Simple KEY=VALUE loader so secrets never live in code. Create a file
# named `.env` next to manage.py with e.g.:
#   FAST2SMS_API_KEY=your_key_here
_ENV_FILE = Path(__file__).resolve().parent.parent / '.env'
if _ENV_FILE.exists():
    for _line in _ENV_FILE.read_text(encoding='utf-8').splitlines():
        _line = _line.strip()
        if not _line or _line.startswith('#') or '=' not in _line:
            continue
        _k, _, _v = _line.partition('=')
        os.environ.setdefault(_k.strip(), _v.strip().strip('"').strip("'"))
# ---------------------------------------------------------------------------


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x92s491sm6n06=j7v4hv_t7#7dk5p!sjp#-#uf+gj3)ehs%k@x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rental',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rentgo_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'rental' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rentgo_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'rent_go',
        'USER': 'root',
        'PASSWORD': 'Anurag@2006',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'rental' / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
#
# Configure EMAIL_HOST (+ user/password/port) in the .env file to send real
# emails. Without it Django uses the console backend and verification codes
# are printed to stdout and shown in-app.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', '').strip()
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587') or 587)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '').strip()
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '').strip()
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', '1') == '1'
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL',
    'Rent&Go <no-reply@rentgo.in>',
)

_PLACEHOLDER_HOSTS = ('', 'PASTE_YOUR_SMTP_HOST_HERE')
if EMAIL_HOST not in _PLACEHOLDER_HOSTS:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


# Google sign-in
# ----------------
# Create a Google OAuth 2.0 Client ID at
# https://console.cloud.google.com/apis/credentials (set the authorised
# JavaScript origin to http://127.0.0.1:8000) and put the id in .env:
#   GOOGLE_OAUTH_CLIENT_ID=xxxx.apps.googleusercontent.com
# The Google button on the auth page only renders when this is set.
GOOGLE_OAUTH_CLIENT_ID = os.environ.get('GOOGLE_OAUTH_CLIENT_ID', '').strip()
GOOGLE_TOKENINFO_URL = 'https://oauth2.googleapis.com/tokeninfo'


# OTP system
# -----------
# OTPs are generated, stored (hashed) and verified in the MySQL database.
# Delivery is pluggable — see rental/otp_service.py:
#   * SMS  : Fast2SMS (enabled automatically when FAST2SMS_API_KEY is set,
#            either as an environment variable or in the .env file).
#   * In-app: OTP shown on the page + printed to the server console —
#            used automatically when no SMS key is configured or SMS fails.
OTP_EXPIRY_MINUTES = 5
OTP_MAX_ATTEMPTS = 5
OTP_RESEND_COOLDOWN_SECONDS = 60

FAST2SMS_API_KEY = os.environ.get('FAST2SMS_API_KEY', '').strip()
FAST2SMS_SENDER_ID = os.environ.get('FAST2SMS_SENDER_ID', '').strip() or 'RENTGO'
FAST2SMS_TIMEOUT_SECONDS = 10
